# Import standard libraries

This analysis has taken inspiration from the research paper:
https://arxiv.org/pdf/1609.08399.pdf

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import glob
import cv2

# Import dataset

The dataset comes in the following form:

HousesInfo.txt: 

Corresponding Images of the houses



Goal: Make the dataset in the following manner:


## Get housing Attributes

In [4]:
def get_house_attributes(iPath):
    cols = ["bedrooms", "bathrooms", "area", "zipcode", "price"]
    df = pd.read_csv(iPath, sep=" ", header=None, names=cols)
    return df

In [6]:
df = get_house_attributes("Houses Dataset/HousesInfo.txt")
df.head()

bedrooms  bathrooms  area  zipcode   price
0         4        4.0  4053    85255  869500
1         4        3.0  3343    36372  865200
2         3        4.0  3923    85266  889000
3         5        5.0  4022    85262  910000
4         3        4.0  4116    85266  971226

In [11]:
def get_images(df, iPath):
    images = []

    for i in df.index.values:
        basePath = os.path.sep.join([iPath, "{}_*".format(i + 1)])
        paths = sorted(list(glob.glob(basePath)))
        outImage = np.zeros((64,64,3), dtype="uint8")
        inImages = []

        for p in paths:
            image = cv2.imread(p)
            image = cv2.resize(image, (32, 32))
            inImages.append(image)

        # Tile images
        outImage[0:32, 0:32] = inImages[0]
        outImage[0:32, 32:64] = inImages[1]
        outImage[32:64, 0:32] = inImages[2]
        outImage[32:64, 32:64] = inImages[3]

        images.append(outImage)
    
    return np.array(images)

In [12]:
images = get_images(df, "Houses Dataset/")
print(images)

[[[[106 146 170]
   [ 94 139 166]
   [125 169 189]
   ...
   [ 77 131 160]
   [ 87  87 117]
   [ 30  34  59]]

  [[145 182 189]
   [107 158 176]
   [ 97 138 168]
   ...
   [ 28  33  63]
   [ 81  86 119]
   [ 71  99 133]]

  [[137 176 190]
   [ 81 128 154]
   [119 162 181]
   ...
   [ 13  12  38]
   [ 68  75 102]
   [143 128 142]]

  ...

  [[ 93 112 137]
   [119 145 175]
   [125 151 180]
   ...
   [ 96 141 175]
   [ 93 151 180]
   [146 179 195]]

  [[111 135 165]
   [114 142 172]
   [124 150 182]
   ...
   [146 188 212]
   [110 162 188]
   [116 166 192]]

  [[107 133 163]
   [113 139 169]
   [135 160 188]
   ...
   [ 98 162 200]
   [146 185 215]
   [153 195 218]]]


 [[[180 204 226]
   [210 225 239]
   [151 192 225]
   ...
   [109 116 135]
   [162 154 157]
   [208 203 214]]

  [[187 210 229]
   [184 202 218]
   [219 228 242]
   ...
   [114 119 140]
   [179 168 170]
   [211 211 221]]

  [[173 197 221]
   [180 203 226]
   [167 194 215]
   ...
   [136 142 155]
   [172 165 163]
   [201 201

# Explaratory Data Analysis (EDA)

# Model Building

## Preprocessing

## Training

## Testing

# Conclusion